# Generated by Django 5.2.8 on 2025-11-29 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_model_doctor_email_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='age',
            new_name='patient_age',
        ),
    ]
