# Generated by Django 6.0 on 2026-01-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_rename_age_appointment_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='your_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
