# Generated by Django 5.2.8 on 2025-11-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_model',
            name='scope',
            field=models.CharField(choices=[('local', 'Local'), ('global', 'Global')], default='local', max_length=10),
        ),
    ]
