# Generated by Django 5.2.8 on 2025-11-24 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('posts', '0004_comment_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='group',
        ),
        migrations.AddField(
            model_name='post_model',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='groups.group'),
        ),
    ]
